name: Build and Release
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# on: [push]
on:
  push:
    tags:
      - 'v*.*.*'
# on:
#   release:
#     types: [created] # Trigger on release creation

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to create releases and upload assets

    # strategy:
    #   matrix:
    #     go_version: ['stable'] # Or your preferred Go version
    #     go_os: [linux, darwin, windows] # Add other OSes as needed

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: npm install
      - run: go generate
      - run: GOOS=darwin go build -o ${{ github.event.repository.name }}_darwin
      - run: GOOS=linux go build -o ${{ github.event.repository.name }}_linux
      - run: GOOS=windows go build -o ${{ github.event.repository.name }}_windows
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ github.event.repository.name }}_${{ matrix.go_os }}
      #     path: ${{ github.event.repository.name }}_${{ matrix.go_os }}
      # - name: Create release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref_name }}
      #   run: |
      #     gh release create "$tag" \
      #         --repo="$GITHUB_REPOSITORY" \
      #         --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
      #         --generate-notes
      # - uses: actions/create-release@v1
      #   id: create_release
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      # - uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ${{ github.event.repository.name }}_darwin
      #     asset_name: ${{ github.event.repository.name }}_darwin
      #     asset_content_type: application/octet-stream
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}_darwin
            ${{ github.event.repository.name }}_linux
            ${{ github.event.repository.name }}_windows

      # use this to avoid using the softprops action
      # https://github.com/ollama/ollama/blob/82658c3eec0cbb70ba558e5310fe3e68436aa583/.github/workflows/release.yaml#L455
      # - run: gh release upload ${GITHUB_REF_NAME} ${{ github.event.repository.name }}_* --clobber
